---
- name: --- install Java ----
  yum:
    name: java
    state: present

- name: --- Set Java Home ----
  shell: |
   echo 'export JAVA_HOME=/usr/java/jdk1.8.0_251-amd64/jre' | tee -a /etc/profile
   echo 'export PATH=$PATH:$JAVA_HOME' | tee -a /etc/profile
   source /etc/profile
